name: Build and deploy Node.js app to Azure Web App - sii-astro

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  APP_NAME: sii-astro

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm clean-install

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Prepare deployment package
        run: |
          mkdir deployment
          cp -r dist deployment/
          cp package.json deployment/
          cp package-lock.json deployment/
          cp entry.js deployment/
          cd deployment
          npm clean-install --production

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'Production'
          package: deployment

      - name: Deployment Status
        if: always()
        run: |
          echo "Deployment finished with status ${{ job.status }}"
          echo "App URL: https://${{ env.APP_NAME }}.azurewebsites.net"